---
title: "Interpreting Disproportionality Forecasts"
author: "Ryan Estrellado"
date: "1/3/2018"
output: html_document
---

# What is a Risk Ratio 

Imagine you are comparing the risk of picking an orange from a crate of fruit to the risk of picking any other fruit from a crate. If the risk of you picking an *orange* from the crate is fifty percent and the risk of you picking *any other fruit* from the crate is 25 percent, the risk of picking an orange is twice that of any other fruit

```{r}
50 / 25
```

Comparing the risk of picking an orange to the risk of picking any other fruit from the crate is a risk ratio. The risk ratio of 2 tells us that you are twice as likely to pick an orange from the crate as any other fruit.

Here's a special education example. If an imaginary school district called Roosevelt School District has a risk ratio score for white students of 2, that means white students are 2 times more likely to be eligible for special education than all other races in that district. 